### ISSUE TITLE
Can react-mobx-vm use with ant-design？

### ISSUE THREAD

**Issue by cag2050** [be-fe/react-mobx-vm#14]
Can react-mobx-vm use with ant-design（ https://ant.design/index-cn ）？

**Comment by imcuttle** [comment]
Hi, @cag2050 ! 
The VM refers to View-model, which means view and  state are binded, if you know mobx-state-tree, it plays the similar role. 

I have tried to use VM with ant-design and [it works fine](https://github.com/big-wheel/iioo/blob/master/packages/iioo-app-mark-live/src/client/entry.js). 

Welcome you to use VM. 🍻
